/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GangsRouteImport } from './routes/gangs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GangsRoute = GangsRouteImport.update({
  id: '/gangs',
  path: '/gangs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/gangs'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/gangs'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/gangs'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GangsRoute: typeof GangsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gangs': {
      id: '/gangs'
      path: '/gangs'
      fullPath: '/gangs'
      preLoaderRoute: typeof GangsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GangsRoute: GangsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesRoute: MatchesRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
